### ISSUE TITLE
Suggestion: add CloudFlow.choose

### ISSUE THREAD

**Issue by mathias-brandewinder** [mbraceproject/MBrace.Core#100]
It would be nice to have the equivalent of Seq.choose on a CloudFlow.

**Comment by palladin** [comment]
It is relative easy to implement 'choose'. I'm wondering if you would like to implement it as an exercise to get a closer look of CloudFlow internals. It would be great to have you as a contributor.

**Comment by mathias-brandewinder** [comment]
Well played :) I was actually thinking the same, super busy this week but I wouldn't mind taking a look.

**Comment by palladin** [comment]
New combinators is the best place to start for new contributors.

**Comment by palladin** [comment]
map and filter combinators are close to choose so it is good start.

**Comment by dsyme** [comment]
It would be great to get a whole host of F# community members' pictures on http://www.m-brace.net/ :) The MBrace code is a joy too - very nice and clean.

**Comment by dsyme** [comment]
@palladin Have you added an up-for-grabs label and list it on http://up-for-grabs.net/?

**Comment by palladin** [comment]
@dsyme Oh... I didn't know the site! I'll check it

**Comment by leafgarland** [comment]
I had a quick go at `CloudFlow.choose`, see https://github.com/leafgarland/MBrace.Core/commit/47b4d9c2da85e7305c178df7fbc810d203eba15e. Is that along the right lines? Wasn't sure if it required a new transformer or would be better done with a combination of the others.

**Comment by eiriktsarpalis** [comment]
@leafgarland looks good to me. Would you mind sending a PR along with a fitting unit test?

**Comment by palladin** [comment]
@leafgarland It is exactly what I had in mind! Add tests and I'm waiting your PR.

**Comment by leafgarland** [comment]
PR done.

I agree with @dsyme, the codebase is lovely - took very little time to find my way around.

**Comment by leafgarland** [comment]
If you are interested in adding other functions, here is a table of most of the collection functions, along with which ones are already present in CloudFlow. If we can remove those that don't apply to CloudFlow then we would have a list of functions to work on.

Function | CloudFlow | Comment
-------- | --------- | -------
`append`| |
`averageBy`| ✓|
`average`| |
`choose` | ✓|
`chunkBySize` | |
`collect` | ✓|
`compareWith` | |
`concat` | |
`contains` | |
`countBy` | ✓|
`distinctBy` | ✓|
`distinct` | ✓|
`empty` | |
`exactlyOne` | |
`except` | |
`exists2` | |
`exists` | ✓|
`filter` | ✓|
`findBack` | |
`findIndexBack` | |
`findIndex` | |
`find` | ✓|
`fold2` | |
`foldBack2` | |
`foldBack` | |
`fold` | ✓|
`forall2` | |
`forall` | ✓|
`groupBy` | ✓|
`head` | |
`indexed` | |
`init` | |
`isEmpty` | ✓|
`item` | |
`iter2` | |
`iter` | ✓|
`iteri2` | |
`iteri` | |
`last` | |
`length` | ✓|
`map2` | |
`map3` | |
`mapFoldBack` | |
`mapFold` | |
`map` | ✓|
`mapi2` | |
`mapi` | |
`maxBy` | ✓|
`max` | |
`minBy` | ✓|
`min` | |
`nth` | |
`pairwise` | |
`permute` | |
`pick` | ✓|
`reduceBack` | |
`reduce` | ✓|
`replicate` | |
`rev` | |
`scanBack` | |
`scan` | |
`singleton` | |
`skipWhile` | |
`skip` | |
`sortByDescending` | ✓|
`sortBy` | ✓|
`sortDescending` | |
`sortWith` | |
`sort` | |
`splitInto` | |
`sumBy` | |
`sum` | ✓|
`tail` | |
`takeWhile` | |
`take` | ✓|
`truncate` | |
`tryFindBack` | |
`tryFindIndexBack` | |
`tryFindIndex` | |
`tryFind` | ✓|
`tryHead` | |
`tryItem` | |
`tryLast` | |
`tryPick` | ✓|
`unfold` | |
`where` | |
`windowed` | |
`zip3` | |
`zip` | |

**Comment by palladin** [comment]
@leafgarland Is it possible to move your comment about new CloudFlow combinators to another discussion thread? Probably here https://github.com/mbraceproject/MBrace.Design
