### ISSUE TITLE
Add CloudFlow.OfHttpFileByLine

### ISSUE THREAD

**Issue by palladin** [mbraceproject/MBrace.Core#102]
It would be really useful to have CloudFlow.OfHttpFileByLine/OfHttpFilesByLine with semantics similar to OfCloudFileByLine/OfCloudFilesByLine  
```
CloudFlow.OfHttpFileByLine "http://www.url.com/big.csv"
|> CloudFlow.filter (fun line -> ...)
|> CloudFlow.take 10
|> CloudFlow.toArray
```
thanks to @tpetricek for the feature request.

**Comment by isaacabraham** [comment]
Related to #69 - would you be able to do something like this?

```CloudFlow.OfHttpFileByLine "foo"
|> CloudFlow.toCloudFile "myfile"```

Ideally given that you're now supporting HTTP downloads in parallel, it'd be nice to generalise that and have a nice combinator for harnessing multiple workers to download to a cloud file in parallel (e.g. blobs support parallel writing, you just supply a start position etc.)

**Comment by palladin** [comment]
I don't think it is possible to have a single output file because you can't calculate apriori the final size and the line offsets as an example 
```
CloudFlow.OfHttpFileByLine "foo" 
|> ClouFlow.filter (fun ...)
|> CloudFlow.map (fun ...)
|> CloudFlow.toCloudFile "myfile"
```
We can follow the "Spark way" use toTextCloudFiles and then stitch together the output files in one final file.

**Comment by isaacabraham** [comment]
Or you could output all of them in a folder with a name at the end a la Hadoop. With the support for CloudFlow.OfTextFilesByLine this becomes a viable possibility. Especially if you were to add a combinator like OfTextFilesByFolder which scanned all files in the supplied path :-)

**Comment by palladin** [comment]
The toTextCloudFiles combinator works a la Hadoop (single dump folder, indexed part output files)
```
let toTextCloudFiles (dirPath : string) (flow : CloudFlow<string>) : Cloud<CloudFile []> = 
```

**Comment by isaacabraham** [comment]
Perfect - I assume that this works in parallel - so that's great.

**Comment by palladin** [comment]
Yep it works in parallel and for more details
https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Flow/Combinators.fs#L456
