### ISSUE TITLE
Cannot add individual NuGet packages

### ISSUE THREAD

**Issue by mathias-brandewinder** [mbraceproject/MBrace.Core#105]
Trying to create an MBrace project by hand, adding the required NuGet packages - and can't add the dependencies I need.
1. Create an F# library (VS2013)
2. Add MBrace.Core 0.9.14-alpha via "manage NuGet packages" in visual studio / Solution Explorer
3. Add MBrace.Flow  0.9.14-alpha 
4. Add MBrace.Stream 0.9.7-alpha -> fails (Updating MBrace.Core 0.9.14-alpha to MBrace.Core 0.9.7-alpha failed)
Additionally, when I try to add MBrace.Azure, I also get a fail, and MBrace.Azure.Client, nothing seems to be happening.

**Comment by eiriktsarpalis** [comment]
Oh, I see. `MBrace.Streams` is just the old name of `MBrace.Flow`. So essentially you're referencing a package that should have been removed from nuget. Will remove it now.

**Comment by dsyme** [comment]
It's been removed, closing this out
