### ISSUE TITLE
FSPickler issue on MBrace

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#108]
This a repro I can make, on 0.6.10, taken from MBrace Starter Kit:

```
#load "credentials.fsx"

open System
open System.IO
open MBrace.Core
open MBrace.Azure
open MBrace.Azure.Client
open MBrace.Flow
open MBrace.Store
open MBrace.Workflows.Cloud

let cluster = Runtime.GetHandle(config)

// this all works
let job = 
    cloud {
        let name = "isaac"
        let date = System.DateTime.Now
        return (sprintf "Hello world %s %A!" name date)
    } 
    |> cluster.CreateProcess

type Person = { Name : string; Age : int }
let isaac = { Name = "Isaac"; Age = 35 }

// this goes pop
let v = CloudValue.New(isaac, "data/isaac") |> cluster.RunLocally
```

With the following error

```Nessos.FsPickler.FsPicklerException: Error serializing object of type 'FSI_0025+Person'. ---> Nessos.Vagabond.VagabondException: type 'FSI_0025+Person' in dynamic assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not correspond to slice```

If you don't run the first ```cloud { }``` and just go straight to the CloudValue it works fine.

**Comment by eiriktsarpalis** [comment]
Thanks. This is a Vagabond issue, really. A temporary workaround would be to send a new computation *after* the definition of person in fsi.
