### ISSUE TITLE
Better Support for Local and Non Azure Setup Options

### ISSUE THREAD

**Issue by sirinath** [mbraceproject/MBrace.Core#110]

**Comment by dsyme** [comment]
Hi @sirinath, 

I know that @eiriktsarpalis and team are very busy completing the technical details for 1.0

It would be great to have you contribute to the guides!  The current content is at https://github.com/mbraceproject/mbrace-docs/tree/master/docs/content.  Just send a pull request with the updates.

Cheers
Don

**Comment by dsyme** [comment]
Treating as duplicate of request #109
