### ISSUE TITLE
Suggestion: Publish an MBrace.Sandbox nuget package

### ISSUE THREAD

**Issue by eiriktsarpalis** [mbraceproject/MBrace.Core#114]
There are many people that have been asking for a way to test MBrace features without needing to create an Azure account, perhaps in the confines of their local machine(s). I suggest we publish a new nuget package, which we could name MBrace.Sandbox, to cater to this request. This would bundle two core features:

1. In-memory execution for MBrace workflows: running cloud workflows with async semantics, optionally with emulated distributed memory semantics and serialization. This is currently possible using the `InMemoryRuntime` object.

2. MBrace.Thespian for the creation of small clusters locally. This would allow users to experiment with MBrace using an API identical to MBrace.Azure but without the need for an Azure subscription. The latest Runtime.Core refactoring also makes this approach friendly to MBrace.StarterKit: both MBrace.Thespian and MBrace.Azure inherit the same `MBraceClient` abstract class, so they could be used interchangeably in the code samples.

Thoughts?

**Comment by palladin** [comment]
For me it is definitely useful to have in a nuget bundle with InMemoryRuntime and Thespian (but I'm talking with the hat of MBrace developer). I think that we need feedback from the users of MBrace with real use cases.

**Comment by krontogiannis** [comment]
![giphy](https://cloud.githubusercontent.com/assets/2443933/8930047/fc9542c8-3532-11e5-87af-d9fecf2f549e.gif)

**Comment by eiriktsarpalis** [comment]
@palladin Here's a recent request by a non-developer https://twitter.com/AntonM2015/status/625980611153502208

**Comment by isaacabraham** [comment]
Feedback I have received from a large proportion of potential users of MBrace is that they would like a local version of MBrace e.g. Thespian for development purposes. I imagine that you might want to be able to plug into e.g. the Azure side for getting to files though!

A slightly different side would be an "on-prem" version of MBrace that would use local resources for the Store etc.. I haven't tried, but I wonder if AzurePack would be of use here.

**Comment by palladin** [comment]
We definitely need to investigate MBrace for on premise Azure scenarios. 
An interesting site is this http://www.microsoft.com/en-us/server-cloud/products/azure-in-your-datacenter/

**Comment by isaacabraham** [comment]
Also see here: http://www.microsoft.com/en-us/server-cloud/products/windows-azure-pack/

I would suggest though getting a simple-to-test version of Thespian out there (even inside the existing starter pack template) would be a valuable exercise.

**Comment by palladin** [comment]
Btw you can use Thespian with your local FileSystem "c:\" or a remote by providing unc path "\\ComputerName\"

**Comment by eiriktsarpalis** [comment]
Fixed in 094fb46c952c832c55b52ea36f1cf657f079496b
