### ISSUE TITLE
Discussion: Make async composition in MBrace workflows optional

### ISSUE THREAD

**Issue by eiriktsarpalis** [mbraceproject/MBrace.Core#115]
The master branch of MBrace.Core currently supports composition with async workflows in its computation expression builders. This means the following overloads have been defined:
```fsharp
type CloudBuilder =
    member Bind : Async<'T> * ('T -> Cloud<'S>) -> Cloud<'S>
    member ReturnFrom : Async<'T> -> Cloud<'T>
```
So rather than having to write
```fsharp
cloud {
    let! x = Cloud.OfAsync <| async { return 1 }
    return! Cloud.OfAsync <| async { return x + 1 }
}
```
you can simply use
```fsharp
cloud {
    let! x = async { return 1 }
    return! async { return x + 1 }
}
```
This is a pretty useful addition but it can be confusing in some cases due to the way it presents type errors. For example
```fsharp
cloud { return! 2 }
```
would yield
```
Error	15	No overloads match for method 'ReturnFrom'.
```
I was wondering if it would make sense to have these overloads provided as extension methods, to be exposed on request, for example by opening the module
```fsharp
open MBrace.Core.Builders.AsyncExtensions
```
Thoughts?

**Comment by palladin** [comment]
I think it ok to have explicit combinators like Cloud.OfAsync (like the familiar Async.AwaitTask) but on the other side I have seen that AsyncSeq has an Bind overload with Async<'T>
https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/master/src/FSharp.Control.AsyncSeq/AsyncSeq.fs#L222

**Comment by dsyme** [comment]
FWIW I think that overload in AsyncSeq is in a different territory because it's T -> Collection<T>.  And MBrace is particularly sensitive to usability issues like error messages because it needs to aim at entry-level programmers
