### ISSUE TITLE
NuGet Version

### ISSUE THREAD

**Issue by sirinath** [mbraceproject/MBrace.Core#123]
The API seems to have changed some what since the last NuGet release. I feel a lot of things will break with the next release. So when will the next release be available?

**Comment by eiriktsarpalis** [comment]
It's still a prerelease package, so it's only natural that things break. Expect this to keep happening as we are approach a 1.0 release.

**Comment by sirinath** [comment]
I know. If you can publish more often util V1 this will help the cause.

**Comment by dsyme** [comment]
@sirinath The latest versions are available for use, e.g. you can now use MBrace 0.12.2 with a locally simulated cluster very easily.  See the getting-started instructions on http://m-brace.net

**Comment by dsyme** [comment]
I think we can close this now 0.12.2 is available.
