### ISSUE TITLE
display/ToString for CloudDirectory

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#14]
Given this

    let dp = cluster.DefaultStoreClient.FileStore.Directory.Create()

this should display the directory name:

    val dp : CloudDirectory

**Comment by dsyme** [comment]
Oh, it does if "dp" is evaluated.  Maybe that's enough

    val it : CloudDirectory =
      MBrace.CloudDirectory {Path = "76b50623-6342-44ea-8324-279e6e93e162";}

**Comment by eiriktsarpalis** [comment]
This has been addressed in 9e2ce2ed8b24809e8b200cd5ffd25094f9fc9cd4

**Comment by dsyme** [comment]
thanks!
