### ISSUE TITLE
Upgrade to FSharp.Core 4.x?

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#140]
Any plans to upgrade to F#4 - and what's the potential knock on effects of doing something like this?

**Comment by eiriktsarpalis** [comment]
As far as libraries are concerned, my opinion is that upgrading to F# 4.0
is a big no-no. F# 4.0 adds a big range of APIs to core which if used will
render the library unusable in older runtimes, even with binding redirects
set. If you'll notice though all worker executables/roles have been
intentionaly moved to F# 4.0. This ensures that MBrace clusters will work
with any core version the client might be using.
