### ISSUE TITLE
Fault Policy does nothing

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#158]
This is on latest Starter Kit.

```fsharp
cloud {
    Console.Clear()
    do! local {
        printfn "TRYING!"
        failwith "hello" }
        |> Cloud.WithFaultPolicy (FaultPolicy.WithMaxRetries 5)
        |> Cloud.Ignore
    return () }
|> cluster.Run
```

I would expect to see the console print "TRYING" five times. I only see it once: -

```
TRYING!
INFO : Completed work item '04aace02-6cd4-4397-9039-58d18a9c5823' after 00:00:00.0066513
INFO : Concurrent work item count decreased to 0/20.
```

What am I doing wrong?

**Comment by palladin** [comment]
There is a big difference between exceptions and faults in MBrace, for a detailed explanation check this http://mbrace.io/starterkit/HandsOnTutorial/10-exceptions-and-fault-tolerance.html#Fault-tolerance

**Comment by isaacabraham** [comment]
OK. There's no support for retries with Exceptions?

**Comment by palladin** [comment]
No, we don't have support for user level exceptions/retry policies. You have to try/catch the exception and re-execute the local/cloud block manually.

**Comment by eiriktsarpalis** [comment]
@isaacabraham Exception fault policies could be easily implemented as a library feature using exception handling.

**Comment by eiriktsarpalis** [comment]
@isaacabraham Fault policies are different, because they require a bit of runtime support.
