### ISSUE TITLE
Allow use of native 64-bit DLLs with Mbrace/Vagabond/Azure

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#17]
(I'm not sure if this is an issue for Core, Vagabond or Azure)

[This sample](https://github.com/elastacloud/mbrace-on-brisk-starter/blob/master/src/Demos/6-nuget-packages.fsx)  shows how to use the Math.NET nugget package as part of MBrace on Azure: 

However, the Math.NET native Intel MKL implementation is about 20x faster than the managed version, for large matrix operations.  To be competitive, and to be cool, we really need to allow the use of Intel MKL native DLLs as part of MBrace jobs on Azure.  I presume workers can in principle run native code.

On the local machine, this is what's needed to activate Intel MKL native:

1. Add this to the paket dependencies:

       nuget MathNet.Numerics.MKL.Win-x64

2. Add this to the script:

       let dllPath = __SOURCE_DIRECTORY__ + @"\packages\MathNet.Numerics.MKL.Win-x64\content"
       System.Environment.SetEnvironmentVariable("Path",System.Environment.GetEnvironmentVariable("Path") + ";" + dllPath)
       Control.UseNativeMKL();

Then matrix multiplications are much, much faster

On the cluster, it is reasonable to expect to have to manually set Control.UseNativeMKL() at the start of each CreateProcess, and even to adjust the Path explicitly (or set call SetDllDirectory). The problem is that we don't know what SomeDirectory is - where is the native DLL located on the cluster? 

```
let invertRandomMatricesJob = 
    cloud { 
        Control.UseNativeMKL();
        Environment.SetEnvironmentVariable("Path",Environment.GetEnvironmentVariable("Path") + ";" + SomeDirectory)
        let m = Matrix<double>.Build.Random(100,100) 
        let x = (m * m.Inverse()).L1Norm()
        return x } 
    |> cluster.CreateProcess
```

It would also be reasonable to have some explicit vagabond registration of native DLLs

Thanks!

**Comment by krontogiannis** [comment]
Hm, does this work:

```fsharp
type Foo () =
    member __.Bar () = ()

let ps = runtime.Run(cloud { return typeof<Foo>.Assembly.Location })
//"C:\Users\kostas\AppData\Local\Temp\mbrace-process-29176\vagabond\FSI-ASSEMBLY_444c5319-e4e7-44a4-8ee2-9c6470efa0fe_2-bzzefxuxsexlkqkpc8f67ae6v24nalxtede6as3h5uerxqvztgja.dll"
```
I believe that Vagabond's [default path](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Runtime.Core/Vagabond/Vagabond.fs#L64) is `%tmp%\mbrace-process-%PID%\vagabond\`

**Comment by dsyme** [comment]
OK, yes, so there's a location to add to the path.  If there's some way to register additional files with Vagabond to go into that location (without changing their name) then I think we might get there.

**Comment by dsyme** [comment]
I suppose we could add the native DLLs as a resource to an assembly being executed, and copy them out to the %tmp% directory before execution, and add the directory to the path....  Will try that in the morning :)

**Comment by palladin** [comment]
One possible solution...
For manual deployments we can add the native dlls (Add As Link) to the worker role project and make sure that the dll is going to be copied in build folder (build action: "content" and  Copy to Output Directory: "Copy always" ).

**Comment by eiriktsarpalis** [comment]
Hi Don,

We've sort of steered away from supporting unmanaged DLL's in Vagabond. Our assumption was that the users would have to preload such dependencies in their homogenous cluster. That said, I was able to make the Math.NET case work in the following way:
```fsharp
#r "paket.exe"
#load "packages/MathNet.Numerics.FSharp/MathNet.Numerics.fsx"

open MathNet.Numerics
open MathNet.Numerics.LinearAlgebra

let initMKL () =
    let dllPath = Directory.GetCurrentDirectory() + @"\packages\MathNet.Numerics.MKL.Win-x64\content"

    if not <| File.Exists "paket.exe" then
        let url = "https://github.com/fsprojects/Paket/releases/download/0.27.2/paket.exe" 
        use wc = new System.Net.WebClient() 
        let tmp = System.IO.Path.GetTempFileName() 
        wc.DownloadFile(url, tmp)
        System.IO.File.Move(tmp, Directory.GetCurrentDirectory() + @"\paket.exe")

    if not <| Directory.Exists dllPath then
        let p = System.Diagnostics.Process.Start("paket.exe", "add nuget MathNet.Numerics.MKL.Win-x64")
        p.WaitForExit()
        let p = System.Diagnostics.Process.Start("paket.exe", "restore")
        p.WaitForExit()

    let pathVar = Environment.GetEnvironmentVariable("Path")
    if not <| pathVar.Contains dllPath then
        Environment.SetEnvironmentVariable("Path", pathVar + ";" + dllPath)
    Control.UseNativeMKL()

let invertRandomMatricesJob = 
    [ for i in 1 .. 200 -> 
        cloud { 
             initMKL()
             let m = Matrix<double>.Build.Random(100,100) 
             let x = (m * m.Inverse()).L1Norm()
             return x } ]
    |> Cloud.Parallel
    |> cluster.CreateProcess
```
My initial attempts involved static constructors and letting Vagabond upload `paket.exe` to the cluster as a dependency but for whatever reason the CLR failed to load it in the AppDomain.

**Comment by palladin** [comment]
@eiriktsarpalis For some weird reason I really like your approach. Because it is generic enough to do everything... like download and install arbitrary software! (like the opencl drivers from intel)

**Comment by krontogiannis** [comment]
I guess if you have your native dlls locally you can just create cloudfiles for them and in your cloudblock download them to your temp folder.

**Comment by palladin** [comment]
With @eiriktsarpalis approach we can handle also the registration of COM DLLs across the cluster.

**Comment by eiriktsarpalis** [comment]
Still, this leaves the burden to the user to remember to load on every possible task in process. Imagine the following:
```fsharp
type NativeDll = { Name : string ; Blob : CloudFile }
with
    static member OfLocalFile (path : string) : Cloud<NativeDll> = ...
    member __.Load() : Cloud<unit> = ...

cloud {
    do! native.Load()
    doNativeStuff ()
    let! _ = 
        Cloud.Parallel 
            [ cloud { do! native.Load() ; doNativeStuff() } ; 
              cloud { do! native.Load() ; doNativeStuff() } ]
    do! native.Load ()
    return nativeStuff()
}
```
I suspect this needs runtime support. Native Dll's could be registered at the cluster level, for instance:
```fsharp
cluster.RegisterNative(pathToNative)
```
This should ensure that dependencies have been preloaded on every worker instance.

**Comment by palladin** [comment]
Yes agree, it needs runtime support. The problem that worries me, is for some scenarios you need to execute arbitrary setup code.

**Comment by eiriktsarpalis** [comment]
You could register lambdas using the same API

**Comment by palladin** [comment]
Maybe something like the following
```
cluster.RegisterNative(pathToNative, fun args -> ...)
```

**Comment by dsyme** [comment]
Yes, that is cool, very, very cool.

FWIW here's the amazing-mobile-native-code-like-you've-never-seen-it-before-approach.  It works :)   But getting the bits from the cloud looks better rather than uploading it.

```
let bytes1 = File.ReadAllBytes(__SOURCE_DIRECTORY__ + @"\packages\MathNet.Numerics.MKL.Win-x64\content\libiomp5md.dll")
let bytes2 = File.ReadAllBytes(__SOURCE_DIRECTORY__ + @"\packages\MathNet.Numerics.MKL.Win-x64\content\MathNet.Numerics.MKL.dll")

// This can take a while first time you run it, because 'bytes2' is 41MB and needs to be uploaded
let mklJob = 
    cloud { let tmpPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)
            if not (File.Exists(tmpPath + "\libiomp5md.dll")) then
                File.WriteAllBytes(tmpPath + "\libiomp5md.dll", bytes1)
            if not (File.Exists(tmpPath + "\MathNet.Numerics.MKL.dll")) then
                File.WriteAllBytes(tmpPath + "\MathNet.Numerics.MKL.dll", bytes2)
            let path = Environment.GetEnvironmentVariable("Path")
            if not (path.Contains(";"+tmpPath)) then 
                Environment.SetEnvironmentVariable("Path", path + ";" + tmpPath)
            Control.UseNativeMKL();
            let m = Matrix<double>.Build.Random(100,100) 
            let x = (m * m.Inverse()).L1Norm()
            return x } 
    |> cluster.CreateProcess

```

One of those DLLs is 41MB so serializing the job take a fair while over WiFi.  But it works!!!

Vagrant = mobile code on steroids :)

**Comment by dsyme** [comment]
This approach could be made fairly tidy by having a single UseMKL() function that guards a region:

let mklJob = 
    cloud { use region = UseMKL()
            let m = Matrix<double>.Build.Random(100,100) 
            let x = (m * m.Inverse()).L1Norm()
            return x } 
    |> cluster.CreateProcess

**Comment by palladin** [comment]
I think that we need something more... imagine the following
```
cloud { use region = UseMKL()
        let m = Matrix<double>.Build.Random(100,100) 
        let x = (m * m.Inverse()).L1Norm() <||> (m * m.Inverse()).L1Norm()
        return x } 
|> cluster.CreateProcess
```

**Comment by palladin** [comment]
We need something analogous to Static constructors for workers... for inserting initialisation code.

**Comment by eiriktsarpalis** [comment]
You still run the risk of a continuation jumping to a different worker context. I think I probably would make sure to only consume it inside non-monadic code.

**Comment by eiriktsarpalis** [comment]
@palladin just brainstorming here, but what if we used the `ResourceRegistry` to keep such initialisations within scope, local or distributed? For example:
```fsharp
cloud {
   use! _ = Cloud.WithWorkerInitializer(fun () -> ...)
   let! _ = foo <||> bar
}
```
That said, I'm still in favour of a global solution, since such code tends to introduce side-effects to the worker instances.

**Comment by palladin** [comment]
ResourceRegistry is our secret weapon, but in order to work we need also a cloudatom as a flag (plus many other things). I'm not sure, I think it is too much.

**Comment by eiriktsarpalis** [comment]
I think I agree..

**Comment by dsyme** [comment]
BTW just inverted 5100 random 150x150 matrices in 26 seconds on a 10-two-core-small-machine cluster.  

I'm really impressed with the fluency of the programming setup - I just moved the Azure slider along to "10-instances", then ran this from F# Interactive (see [this sample](https://github.com/elastacloud/mbrace-on-brisk-starter/))

```
let cluster = Runtime.GetHandle(config)

let mklJob = 
 [ for i in 0 .. 50 ->
    cloud { UseMKL()
            let results = 
                [ for i in [ 0 .. 100 ] do 
                     let m = Matrix<double>.Build.Random(150,150) 
                     yield (m * m.Inverse()).L1Norm() - 1.0 ]
            return List.average results } ]
    |> Cloud.Parallel
    |> cluster.CreateProcess

```
then got this kind of utilization:
```
 MBraceWorkerRole_IN_0  RD0003FF4BE325    57.41 / 2      28.13 / 3583.00       354.70 / 87637.78    0 / 2        3064  02/03/2015 22:44:41 +00:00  02/03/2015 23:33:26 +00:00  True      
 MBraceWorkerRole_IN_1  RD0003FF4B9D66    45.35 / 2      35.25 / 3583.00        100.49 / 324.65     1 / 2        2032  02/03/2015 23:22:24 +00:00  02/03/2015 23:33:25 +00:00  True      
 MBraceWorkerRole_IN_8  RD0003FF4BE8F9    28.39 / 2      32.32 / 3583.00        140.06 / 163.82     1 / 2        1044  02/03/2015 23:22:26 +00:00  02/03/2015 23:33:25 +00:00  True      
 MBraceWorkerRole_IN_9  RD0003FF4B91C6    47.81 / 2      34.13 / 3583.00       160.42 / 31770.52    1 / 2        3032  02/03/2015 23:22:28 +00:00  02/03/2015 23:33:25 +00:00  True      
 MBraceWorkerRole_IN_3  RD0003FF4B8A01    84.33 / 2      29.14 / 3583.00      440.37 / 133310.78    1 / 2        3716  02/03/2015 23:22:31 +00:00  02/03/2015 23:33:25 +00:00  True      
 MBraceWorkerRole_IN_2  RD0003FF4BDD54    50.72 / 2      28.13 / 3583.00        89.66 / 111.26      1 / 2        3588  02/03/2015 23:22:34 +00:00  02/03/2015 23:33:26 +00:00  True      
 MBraceWorkerRole_IN_5  RD0003FF4B9F4D    63.25 / 2      35.92 / 3583.00      389.29 / 100322.09    0 / 2        3936  02/03/2015 23:22:36 +00:00  02/03/2015 23:33:25 +00:00  True      
 MBraceWorkerRole_IN_4  RD0003FF4BA910    33.96 / 2      32.15 / 3583.00       213.98 / 47319.45    1 / 2        3308  02/03/2015 23:22:37 +00:00  02/03/2015 23:33:25 +00:00  True      
 MBraceWorkerRole_IN_7  RD0003FF4BC621    51.06 / 2      31.68 / 3583.00        145.47 / 199.53     1 / 2        3236  02/03/2015 23:22:41 +00:00  02/03/2015 23:33:25 +00:00  True      
 MBraceWorkerRole_IN_6  RD0003FF4BCBDE    54.55 / 2      30.64 / 3583.00       168.98 / 30519.97    1 / 2        3104  02/03/2015 23:22:48 +00:00  02/03/2015 23:33:25 +00:00  True      
```

Then deallocated the cluster 10 minutes later.  That's really smooth.

The UseMKL() function is as before:

```
let bytes1 = File.ReadAllBytes(__SOURCE_DIRECTORY__ + @"\packages\MathNet.Numerics.MKL.Win-x64\content\libiomp5md.dll")
let bytes2 = File.ReadAllBytes(__SOURCE_DIRECTORY__ + @"\packages\MathNet.Numerics.MKL.Win-x64\content\MathNet.Numerics.MKL.dll")
let UseMKL() = 
    let tmpPath = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location)
    if not (File.Exists(tmpPath + "\libiomp5md.dll")) then
        File.WriteAllBytes(tmpPath + "\libiomp5md.dll", bytes1)
    if not (File.Exists(tmpPath + "\MathNet.Numerics.MKL.dll")) then
        File.WriteAllBytes(tmpPath + "\MathNet.Numerics.MKL.dll", bytes2)
    let path = Environment.GetEnvironmentVariable("Path")
    if not (path.Contains(";"+tmpPath)) then 
        Environment.SetEnvironmentVariable("Path", path + ";" + tmpPath)
    Control.UseNativeMKL()
```

**Comment by dsyme** [comment]
FWIW the Brisk getting-started examples now include the upload-the-MKL-DLLs-example. https://github.com/elastacloud/mbrace-on-brisk-starter/pull/42/files#diff-811695910cf55f79886c9a681cfec76aR46

**Comment by eiriktsarpalis** [comment]
Starting from https://github.com/mbraceproject/MBrace.Azure/commit/ff18dfeb3f80bfeb2e1fe1f9842c178ac667b823 MBrace.Azure offers experimental support for uploading native assemblies. Here's how it works:
```fsharp
#load @"script-packages/packages/MathNet.Numerics.FSharp/MathNet.Numerics.fsx"

open MathNet.Numerics
open MathNet.Numerics.LinearAlgebra

// manually register native dependency files to client state
let contentDir = __SOURCE_DIRECTORY__ + @"/script-packages/packages/MathNet.Numerics.MKL.Win-x64/content/"
Runtime.RegisterNativeDependency <| contentDir + "libiomp5md.dll"
Runtime.RegisterNativeDependency <| contentDir + "MathNet.Numerics.MKL.dll"
Runtime.NativeDependencies // verify that native dependencies are loaded

// submit computation to the cloud
let firstMklJob = 
   cloud { Control.UseNativeMKL()
           let m = Matrix<double>.Build.Random(200,200) 
           return m.LU().Determinant }
    |> runtime.CreateProcess
```

**Comment by dsyme** [comment]
That's great.  When Brisk gets updated lets update the getting-started samples with this

**Comment by eiriktsarpalis** [comment]
@dsyme The samples have been updated in [MBrace.StarterKit](https://github.com/mbraceproject/MBrace.StarterKit).
