### ISSUE TITLE
Is CloudAttribute still needed?

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#23]
Is this still needed now Vagrant is being used?

https://github.com/mbraceproject/MBrace.Core/blob/e6d1b9de09cc72d59dc9bb0ac9a25a374d011543/src/MBrace.Core/Continuation/Workflow.fs#L39

**Comment by eiriktsarpalis** [comment]
We still keep [this](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Runtime.Core/Compiler/Compiler.fs#L60) library implementation that traverses quotations looking for non-serializable bindings inside cloud workflows before uploading the computation. We haven't included this in the Azure implementation. It's kind of useful in a sense, but it doesn't beat not having to put the computation inside quotation literals. It is quite possible that this will be deprecated, in the end.

**Comment by dsyme** [comment]
OK, thanks, I see.
