### ISSUE TITLE
CloudAtomUtils shows empty in intellisense

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#24]
CloudAtomUtils is showing as empty in intellisense, because it has an extension member.  It would be better if it didn't show at all.  I actually didn't think such modules showed in F# intellisense but apparently they do (WebExtensions from FSharp.Core also shows).  Anyway, it would be nice if there were some way that it didn't show: clean intellisense menus are a blessing for users.

https://github.com/mbraceproject/MBrace.Core/blob/e6d1b9de09cc72d59dc9bb0ac9a25a374d011543/src/MBrace.Core/Store/Atom.fs#L29

**Comment by eiriktsarpalis** [comment]
Would it be possible to allow extension members outside of modules? I have always found this particular restriction annoying.

**Comment by dsyme** [comment]
@eiriktsarpalis - that's not easy, though by all means add an http://fslang.uservoice.com issue to track it

I'm going to close this issue since it's a very minor thing and is really an F# Intellisense glitch
