### ISSUE TITLE
CloudFileReader - is it needed

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#25]
I notice the CloudFileReader type, https://github.com/mbraceproject/MBrace.Core/blob/597057804bd7d991c82f3366541283699769e5c9/src/MBrace.Streams/Readers.fs#L7

Does this need to be public anymore, now that CloudFile.ReadAllLines and friends are there?  In what case would the user refer to these explicitly?

**Comment by krontogiannis** [comment]
The `CloudFileReader` type is part of the `MBrace.Streams` namespace and is meant to be used as an argument in [`CloudStream.ofCloudFiles (reader : System.IO.Stream -> Async<'T>) (sources : seq<CloudFile>) : CloudStream<'T> `](https://github.com/mbraceproject/MBrace.Core/blob/597057804bd7d991c82f3366541283699769e5c9/src/MBrace.Streams/CloudStreams.fs#L116).

I believe at some point at least the case with the `ReadLines` reader will become a separate method like: `CloudStream.ofCloudFileLines` or sth.

**Comment by dsyme** [comment]
OK, that makes sense.  I'll close this for now.
