### ISSUE TITLE
CloudStream.groupBy, distinct etc.?

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#28]
Are there plans to add groupBy, sortByDescending, distinct and other such operators to CloudStream? Perhaps the F# community can contribute if you make available a roadmap based on [this table](https://github.com/Microsoft/visualfsharp/wiki/F%23-4.0-Status)?

**Comment by eiriktsarpalis** [comment]
Definitely, these should also be relatively straightforward to implement on top of [`CloudStream.foldBy`](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Streams/CloudStreams.fs#L356). We were actually discussing about adopting the FSharpLangDesign format for tracking all MBrace-related work items.

**Comment by eiriktsarpalis** [comment]
I just created an [MBrace.Design](https://github.com/mbraceproject/MBrace.Design) repo which contains a [list of streams combinators](https://github.com/mbraceproject/MBrace.Design/blob/master/MBrace.Streams/combinators.md). Format has been shamelessly ripped of from FSharpLangDesign.

**Comment by dsyme** [comment]
Cool.   foldBy should perhaps be renamed - fold has a very linear, left-to-right feel. I didn't realize by its name what a powerful key+reduce primitive it was.

**Comment by biboudis** [comment]
Something with collect + groupBy you mean?

(e.g., http://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html )

**Comment by dsyme** [comment]
Sounds reasonable (or collect + reduce)

**Comment by palladin** [comment]
Maybe we can rename fold/foldBy to reduce/reduceBy but I was hoping to keep the reduce name availabe for other combinators like CloudStream.reduce : CloudStream<'T> -> ('T -> 'T -> 'T) -> Cloud<'T>. Btw the PSeq has also a fold combinator https://github.com/fsprojects/FSharp.Collections.ParallelSeq/blob/master/src/FSharp.Collections.ParallelSeq/pseq.fs#L40

**Comment by anirothan** [comment]
groupBy/sortBy*/distinct*/average* implemented as of https://github.com/mbraceproject/MBrace.Core/pull/80
