### ISSUE TITLE
CloudCell.Delete?

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#31]
Given we can delete immutable cloud files, I believe it should be possible to delete immutable CloudCell values.  

I realise this breaks the caching model, and is thus logically part of the storage-management API (like CloudFile.Delete and so on).  But it seems necessary to allow this programmatically somehow.

**Comment by krontogiannis** [comment]
`CloudCell` implements `ICloudDisposable`. Just seems like a static method is missing for this one

**Comment by dsyme** [comment]
Ah thanks - yes, a static method is needed.  Those interface so undiscoverable, and to be honest I haven't found myself using any of the interface-based functionality on any MBrace abstractions yet

**Comment by eiriktsarpalis** [comment]
Fixed as of https://github.com/mbraceproject/MBrace.Core/commit/0aae7e5e37221207f2ed85cdb66be5918a34fc0c
