### ISSUE TITLE
Food for thought: Can CloudSequence and CloudVector be one?

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#39]
From what I can tell a CloudSequence is just a CloudVector with a single partition.

Have you thought of simplifying these and just have the one main type ``CloudVector`` with CloudSequence renamed to ``CloudVectorPartition``?

I suppose it depends if an un-partitioned CloudSequence has substantial independent utility either as a primitive or as something commonly used.  

Even if it exists as a question, I find myself wondering if CloudSequence should be taught in the primary learning sequence, or if people should just go straight to CloudVector. See https://github.com/dsyme/mbrace-docs/blob/fix-2/docs/content/programming-model.fsx#L377 for example.

This issue is just food for thought about how to keep simplifying the API and the primary teaching sequences.  Close it once it is digested :)

cheers
don

**Comment by eiriktsarpalis** [comment]
Yes, we're currently investigating changes in this part of the API. Our primary motivation is that parallelising computation over a single CloudSequence is currently unsupported. MBrace.Streams assumes that CloudVector instances carry homogeneous partitioning for scaling to be achieved and this is clearly a weakness that needs to be addressed. Our plan is to utilize Azure's block blobs for parallelising access to single files. In this scheme, the idea of a 'partition' becomes blurred so I think we need to reevaluate design for those primitives.

I've been thinking about renaming the current `CloudSequence<T>` to something like `CloudChunk<T>` or `CloudFile<T>` or `CloudValues<T>` and then define an interface `ICloudSequence<T>` which would be implemented by both this type and `CloudVector<T>`. This interface would indicate information on 'partionability' to be consumed by libraries such as MBrace.Streams.

**Comment by dsyme** [comment]
OK, thanks, understood.  I'll close this now since the input has been received :)
