### ISSUE TITLE
Question: Async --> Local 

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#40]
I've been looking at running a web server on an MBrace worker, just out of curiosity. That leads to a question about what we do if we lose the ``cloud { ... }`` or ``local { .. }`` monadic context and whether that context can be locally captured and restored.

In particular, the handlers for all web server frameworks are in terms of ``Task<T>``, ``Async<T>`` or synchronous handlers.  

I'd like these handlers to be able to "do things" on the cluster.  Of course they could rebind to the cluster itself as if they were a client. But I'm wondering if there is any way that handlers (which are logically running as part of a ``cloud { ... } ``) can do ``Local`` or ``Cloud`` actions even though we're no longer in a cloud monadic context but rather in an async handler that was registered by the monadic context.

That is, can we allow handlers to do an invoke as if they were a ``local { ... } ``.  That may require the equivalent of an unsafe-perform-IO or a Local.FromContinuations backdoor.

t's not necessarily something we want to encourage of course, I'm just wondering.

Here's the rough structure of the web server process:
```
let handler() = async { ... }  // some async handlers to handler requests

let server app = 
  cloud { 
    do! Cloud.Logf "starting web server job..." 

    // Get the endpoint we have to bind to 
    let httpEP = RoleEnvironment.CurrentRoleInstance.InstanceEndpoints.["Endpoint2"].IPEndpoint

   // Start the Suave server, binding to the endpoint
    do Async.Start (async { startWebServer config handler  })

    // Wait for cancellation
    ...
    do! Cloud.Logf "exiting..." 
    return logLines()
    }
```

**Comment by eiriktsarpalis** [comment]
Yes, it's possible. For instance
```fsharp
open MBrace.Continuation

#nowarn "444" // internal API generates compiler warning, disable

cloud {
    let! ctx = Cloud.GetExecutionContext()
    let asyncWorkflow = Cloud.ToAsync(cloud { ... }, ctx.Resources, ctx.CancellationToken)
    return Async.StartAsTask asyncWorkflow
}
```

**Comment by dsyme** [comment]
Great! Will try that tomorrow!

**Comment by dsyme** [comment]
That works, thanks
