### ISSUE TITLE
CloudCell isn't obvious how to use.

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#41]
I have a text file in blob storage. I can get to it via CloudFile easily enough, but I want to cache it. So I can't use CloudFile for this, I need CloudCell. But the API doesn't have any easy way for me to either go from a CloudFile to a CloudCell, nor can I easily do e.g. CloudCell.Load "myfile".

Do we even need two abstractions for a reference to a remote bit of data?

**Comment by dsyme** [comment]
It seems OK to have two abstractions - one is an immutable typed value with implied serialization, the other is an immutable normal text/binary file. (But as both are considered immutable apart from deletion, caching should be available on both.)

I would actually expect more "remote bit of data" abstractions (either in the core or defined by the user out of primitives) - CloudCell is like a vanilla blob that doesn't give any particular access advantages (like partitioning, indexing, reading line-by-line, random access etc.) - other abstractions like CloudFile and CloudVector should give specific additional capabilities.

**Comment by isaacabraham** [comment]
Just to follow up on this - having spoken with @eiriktsarpalis. My understanding is that: -

1. CloudFile is equivalent to the file system - low level access but not much more.
2. CloudCell is a library feature that allows abstraction of abitrary values on top of the store. The caching part is an "added benefit" provided by a separate interface and could be provided externally from CloudCell.

I think a lot of the confusion I (and others) have seen with these two APIs is: -

1. Documentation is lacking (both on the web and in the XML comments).
2. There's some overlap between the two that needs to be made explicit.
3. There were some initial bugs with CloudCell.
4. The caching part on CloudCell suggests that you "must" use CloudCell to get caching when it could be done somehow else as well.

**Comment by eiriktsarpalis** [comment]
I think my one-on-one sessions with both @isaacabraham  and @mathias-brandewinder have illustrated the power of this approach. I would recommend we continue with more sessions over skype both in developing examples/tutorials and in review of the core API.

**Comment by isaacabraham** [comment]
@eiriktsarpalis. Yes, agreed - I found it very useful. However, obviously this isn't going to be possible for every user of MBrace (let's assume for a moment that it becomes a massive Hadoop-killer ;-)) so we need to think about how to avoid the need to 1-to-1 sessions for others. But it was probably a useful exercise for you to see me floundering around trying to get it "working" :-)

Whilst I believe that there's definitely a use-case for both "file system" access and "value-on-the-cluster" semantics - the latter is obviously extremely useful - there's probably just some tweaking and maybe even restriction of the core CloudCell API to make the distinctions clear.

IMHO. :-)

**Comment by eiriktsarpalis** [comment]
I was mostly thinking of it as something that we should do as we prepare for a 1.0 release. Hopefully this will clear away some of the more obvious issues with the API before many people get to use it.

**Comment by isaacabraham** [comment]
Yes a good idea - let's schedule something from that when it's appropriate.

**Comment by dsyme** [comment]
Closing this as it's an old discussion
