### ISSUE TITLE
CloudKeyValueStore as a primitive

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#52]
Some programmatic distributed compute frameworks I've seen make distributed, partitioned key-value stores the primary data structure in the framework )in some cases it is more or less the only data primitive).  This obviously also maps well onto table storage. CloudVector can be seen as a special case of a distributed KVS.

In any case, I'm wondering whether this direction has been considered.  

Thanks
Don

**Comment by palladin** [comment]
Currently CloudAtom https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Core/Store/Atom.fs
offers some functionality for fine-grained updates (The azure implementation uses table storage and for a possible yarn implementation we can probably map it to HBase)

**Comment by eiriktsarpalis** [comment]
An `ICloudDictionary` abstraction has been included in #59
