### ISSUE TITLE
Functions that take in CloudFiles are not obvious

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#62]
There are many functions on e.g. CloudCell that take in CloudFiles but the method naming often simply says "File" or "Path"; I actually thought that these were local file system paths! Either this should be renamed + commented appropriately in the XML comments, or these methods could be typed to take in a CloudFile instead of just a string.

**Comment by eiriktsarpalis** [comment]
This has been fixed in 811d73ad73b70595a682e70ff3aabf3c19adb560
