### ISSUE TITLE
CloudFlow.collect requires an explicit seq

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#63]
The signature of ```CloudFlow.Collect``` looks like: -

```val inline collect : f:('T -> seq<'R>) -> flow:CloudFlow<'T> -> CloudFlow<'R>```

Even if you return e.g. an ```array<'R>```, the compiler will complain about this and you need to e.g. ```Seq.ofArray``` at the end of the lambda. Could the signature be changed to something like this?

```val inline collect : f:('T -> #seq<'R>) -> flow:CloudFlow<'T> -> CloudFlow<'R>```

**Comment by palladin** [comment]
Thanks for the feedback! Fixed in https://github.com/mbraceproject/MBrace.Core/commit/0078c1d048606ae8e17c4f995aed8af87e77a8ab

**Comment by isaacabraham** [comment]
@palladin  Sweet, thanks.
