### ISSUE TITLE
CloudFlow to CloudFile

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#64]
Having a combinator to go from ```CloudFile``` to ```CloudFlow``` is very useful, but the logical end of this would be to also have a ```toCloudFile``` combinator as well - this would truly allow us to perform data workloads which revolve around reading a file (or set of files), performing some arbitrary operations on it, and outputting the result back to a file. Of course I would imagine that the implementation of this would also run in parallel rather than fork/ join for performance reasons (as has been done AFAIK for the ```fromCloudFileAsLines``` implementation).

**Comment by eiriktsarpalis** [comment]
I suppose you mean this as an equivalent of the Spark `saveAsTextFile(path)` [method](https://spark.apache.org/docs/latest/programming-guide.html#actions). In MBrace.Flow this could have the following type signature:
```fsharp
CloudFlow.toTextFile : CloudFlow<string> -> Cloud<CloudFile>
```

**Comment by eiriktsarpalis** [comment]
As of 0.9.9, for cases where the format is not text and the requirement for a single file is not needed, you can always use `CloudFlow.toCloudVector`. This forces computation of the flow and persists the results, resulting in a new CloudFlow instance. This is roughly equivalent to the Spark persist() method.

**Comment by isaacabraham** [comment]
Yeah, that might work (although as discussed, the current naming might be non-obvious) - I'm just thinking of the typical Hadoop scenario - input file -> do some distributed processing -> output file.

**Comment by palladin** [comment]
I think that hadoop creates n output files where n is the number of reducers. I'm not so sure how it can work with a single file?

**Comment by palladin** [comment]
Or we can follow the Hadoop/Spark way and create a cloudfile for each partition.
```
saveAsTextFiles : ClouFlow<string> -> (fileName : string) -> Cloud<CloudFile[]>
```

**Comment by isaacabraham** [comment]
@palladin: yes, each reducer outputs their own file - I vaguely recall there being an option to merge the outputs into one once done (although I might be wrong here) - one approach is to have each MBrace flow job output its own file as per Hadoop as a first step; secondly, see if there's a way to have a single final job to stitch the individual files together. Obviously this would work differently with e.g. Azure Blobs rather with a local file system and might not be possible.
