### ISSUE TITLE
CloudVector performance / usage question

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#65]
I have a CloudFlow that is operating over a 100mb file split into around 2million rows. I've done a relatively simple set of maps and filters on the flow, and wanted to persist / caching the results in memory across the cluster so that I can then repeatedly perform further cloud flows operations starting from here.

I started with a flow as follows: -

```fsharp
let results =
    [ fileRef ]
    |> CloudFlow.ofCloudFilesByLine
    |> CloudFlow.filter(fun row -> not (row.StartsWith "Acc_Index")) // skip header
    |> CloudFlow.map(fun row -> Casualties.ParseRows row |> Seq.head) // raw text to provided type
    |> CloudFlow.countBy(fun row -> row.Sex_of_Casualty)
    |> CloudFlow.toArray
    |> cluster.CreateProcess
```

This took around 60 seconds to run. I then modified the above code as follows: -

```fsharp
let results =
    [ fileRef ]
    |> CloudFlow.ofCloudFilesByLine
    |> CloudFlow.filter(fun row -> not (row.StartsWith "Acc_Index")) // skip header
    |> CloudFlow.map(fun row -> Casualties.ParseRows row |> Seq.head) // raw text to provided type
    |> CloudFlow.toCachedCloudVector
    |> cluster.CreateProcess
```

This process took over 2.5 minutes to run.
```
 Name                        Process Id     Status  Completed  Execution Time            Jobs           Result Type                                                                                          Start Time                  Completion Time            
 ----                        ----------     ------  ---------  --------------            ----           -----------                                                                                          ----------                  ---------------            
4c3352570aff44e5bf12af4b26d2ae06  Completed  True       00:01:10.7470280    0 /   0 /  13 /  13  (int * int64) []                                                                                     20/04/2015 17:34:15 +00:00  20/04/2015 17:35:26 +00:00 
3a57b4cb90da442d97baac5327c3283e  Completed  True       00:02:33.5285346    0 /   0 /   5 /   5  CloudVector<(string * int * int * int * int * int * int * int * int * int * int * int * int * int)>  20/04/2015 17:39:46 +00:00  20/04/2015 17:42:20 +00:00 
```

When I observed the workers, only one of them seemed to be doing much - it had high network bandwidth for a while, and ended up with higher memory utilization than the others: -

```
Id                     Hostname        % CPU / Cores  % Memory / Total(MB)  Network(ul/dl : kbps)   Jobs   Process Id  Initialization Time         Heartbeat                   Is active 
 --                     --------        -------------  --------------------  ---------------------   ----   ----------  -------------------         ---------                   --------- 
 MBraceWorkerRole_IN_3  RD0003FF44A489    2.96 / 4       21.75 / 7167.00        174.19 / 276.71     0 / 32        1256  17/04/2015 10:19:42 +00:00  20/04/2015 17:50:40 +00:00  True      
 MBraceWorkerRole_IN_1  RD0003FF44F5E6    2.52 / 4       16.92 / 7167.00        137.08 / 215.45     0 / 32        1012  17/04/2015 10:19:45 +00:00  20/04/2015 17:50:40 +00:00  True      
 MBraceWorkerRole_IN_2  RD0003FF44EC26    4.09 / 4       16.24 / 7167.00        165.88 / 180.45     0 / 32        1152  17/04/2015 10:19:52 +00:00  20/04/2015 17:50:39 +00:00  True      
 MBraceWorkerRole_IN_0  RD0003FF44F1F5    3.14 / 4       16.20 / 7167.00        184.52 / 273.63     0 / 32        2252  17/04/2015 10:19:59 +00:00  20/04/2015 17:50:39 +00:00  True      
```

What I don't get is - what exactly have I done by calling ```toCachedCloudVector```? What has it done? Why was there high network upload?

Am I using the correct abstraction to get the correct behaviour i.e. store in memory the results of that flow so that I can use it repeatedly afterwards.

**Comment by eiriktsarpalis** [comment]
`toCachedCloudVector` will 1) force computation of provided flow 2) persist computed data as CloudVector partitions and 3) cache partitions in-memory across the cluster. In that sense it is natural that it might take some additional time to compute, however this seems a bit overblown. If the worker reporting is accurate, this certainly smells like a bug. Not sure if core or azure though.

You are using 0.6.5 no?

**Comment by isaacabraham** [comment]
Yes, so this might have changed since then. I was more interested in the memory stats and the concentration across the cluster.
The additional time could be because I'm not doing the countby so persisting the whole data set. But its a bit of an unknown to me in terms of what happens.
Once it returns it's very quick for subsequent queries - 3-4 seconds for the countBy.

**Comment by krontogiannis** [comment]
Does CloudFlow.ofCloudFilesByLine parallelize in case of a single CloudFile?

**Comment by eiriktsarpalis** [comment]
@krontogiannis it should do at least.

**Comment by krontogiannis** [comment]
Sorry, i dont mean using local parstream. In case of a single cloudfile ofCloudFile**s**ByLine will execute in a single worker or not? Isn't ofCloudFileByLine more appropriate?

**Comment by eiriktsarpalis** [comment]
@krontogiannis doh! Didn't notice that extra **s** there. So no, this will send all the workload to a single worker. And this explains the worker behaviour.

@isaacabraham you need to use `CloudFlow.ofCloudFile_ByLine` which takes a single file as argument. Confusing I know, we'll need to have this sorted out in the upcoming releases.

**Comment by isaacabraham** [comment]
Good spot! Ok that makes sense given what we discussed last week. I'll try it again and see what behaviour I get.

Once you have a cloud vector though, what is the behaviour for any cloud flow operations - I assume that those are parallelised.

**Comment by eiriktsarpalis** [comment]
Not necessarily. When running `toCloudVector` created partitions correspond to the number of workers that act on the flow. In this case, cloud vector will only have one partition and thus won't be parallelisable. I think there's definitely room for improvement here.

**Comment by isaacabraham** [comment]
Yes - especially if you add nodes later on (or create a new cluster that connects to an existing configuration).

**Comment by isaacabraham** [comment]
OK - looks like 0.6.5 doesn't have the ofCloudFile() method. It does have the ofTextFileByLine though, that I believe will have the correct behaviour of parallelising.

**Comment by isaacabraham** [comment]
Yes - that worked - I'm getting CPU and network utilisation equally across the cluster now as well as rising memory on all nodes.

**Comment by isaacabraham** [comment]
Another question on this - when I'm converting a CloudFlow into a CloudVector, I'm seeing a large amount of data uploaded /from/ worker nodes. Let's say I'm working with a relatively large file (or set of files) in the filestore e.g. 2GB. I do a couple of flow operations, some filters and maps, and then I want to cache it in memory because I want to run a number of queries against that set. This takes /ages/ - like > 10minutes on a 4 node cluster.

Is the upload of data I'm seeing the serialized output of the cloud vector to the filestore? If so - is there a way to opt-out of this? If I just want something transcient in memory, I don't want to also bear the cost (not just time but financial if using e.g. Azure) of uploading a serialized file that may be many GB into the store.

**Comment by eiriktsarpalis** [comment]
I had precisely this discussion with @palladin earlier today. We were talking about incorporating an api similar to the spark [persist method](https://spark.apache.org/docs/latest/programming-guide.html#rdd-persistence). I gather that the current CloudFlow abstraction is hard to reconcile with a `MEMORY_ONLY` configuration, since the latter requires recomputation in the event of faults which the former is difficult to admit. I guess it's workable, but some reengineering of the library might be required.

**Comment by isaacabraham** [comment]
cool - good to know we're thinking along the same lines. I wouldn't mind even if it didn't have fault handling initially - "if it makes it into the cache it worked, otherwise it failed" sort of thing.

**Comment by isaacabraham** [comment]
Another alternative might be to just write locally to the OS disk on the worker node - this is a physical disk that would have reasonably good performance.

**Comment by isaacabraham** [comment]
Just a quick nudge - any plans to progress this in either: -

* In-memory only model
* Push to OS disk in Azure implementation i.e. not blob storage
* Use some distributed caching model (again, Azure Cloud services come with this for free)

**Comment by eiriktsarpalis** [comment]
So there's [this branch](https://github.com/mbraceproject/MBrace.Core/tree/caching-refactoring) that brings cached values as an abstract primitive. Any changes w.r.t. the in-memory model will have to take this primitive into consideration as soon as it becomes available.

**Comment by isaacabraham** [comment]
How does that fit with things like CloudValue - is it an underlying primitive that will be utilised by that?

My understanding is that CloudVector (I forget the new name!) already supports in-memory caching - it's more that I would like the capability of disabling the "to disk" spooling that happens automatically. Given that you can't re-read from it, I'm still not clear of the real value of them except for the use case if a node goes down.

**Comment by eiriktsarpalis** [comment]
The idea is to promote CloudValue to an ADT, rather than being a concrete implementation over the store as it stands right now. CloudValues can be created applying a [StorageLevel](https://github.com/mbraceproject/MBrace.Core/blob/caching-refactoring/src/MBrace.Core/Store/CloudValue.fs#L10) parameter, just like spark.

**Comment by isaacabraham** [comment]
Ah ok this I like. So the question with something like persisted cloud flow would be how to capture that against the need for partitioning the data across a cluster (unless this is done at a higher level)
________________________________

**Comment by eiriktsarpalis** [comment]
Yes. It's still something that needs to be worked out after this is merged with the master branch, there are many details that need to be ironed out /cc @palladin

**Comment by isaacabraham** [comment]
Can this be closed now?
