### ISSUE TITLE
Re-reference an already-created CloudVector

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#67]
How can you get a handle to a CloudVector that you already created in e.g. a previous FSI session?

**Comment by eiriktsarpalis** [comment]
You can't at the moment. CloudVector<> (now known as PersistedCloudFlow<>) is just an object containing a collection of CloudSequences. In that sense there is no singular point of reference that can be recovered from store.

For now, you could try doing the following
```fsharp
let! pcf : PersistedCloudFlow<int> = [|1 .. 10000|] |> CloudFlow.OfArray |> CloudFlow.map ((+) 1) |> CloudFlow.persist
let! ref : CloudValue<PersistedCloudFlow<int>> = CloudValue.New pcf
let path = ref.Path // record the path for future use
```
then in future sessions
```fsharp
let! ref = CloudValue.OfCloudFile<PersistedCloudFlow<int>>(path)
let! pcf = ref.Value // recovered RDD
```
I guess it would make sense to keep around a partition manifest for persisted flows. In essense it would create a nice wrapping around the logic I described above.

**Comment by isaacabraham** [comment]
Exactly. You lose some of the benefits of persisted cloud vectors if they are not able to re-attach to them. Even worse, because they are persisted to blobs on the Azure side (I think that this should really go to the VM local physical temp disk) they stay forever unless you manually clean them up.

**Comment by isaacabraham** [comment]
Ref #65

**Comment by isaacabraham** [comment]
Just wondering if the 1.0 milestone for this is the ability to "re-reference" a cloud vector or the ability to have in-memory only / temp storage disk for persisted cloud vectors / RDDs?

**Comment by eiriktsarpalis** [comment]
I think it should be the former. In-memory storage needs significant redesign of the Flow library.

**Comment by isaacabraham** [comment]
Do you think it's going to be possible to at least turn off the persistant caching in the meantime? Or redirect to local FS? The performance of CloudVectors over large datasets is so adversely affected by the performance of blob storage that I'm currently shying away from using them.

**Comment by eiriktsarpalis** [comment]
Yes, just avoid adding CloudFlow.persist at the end of your pipeline. Pure
cloudflows will re-evaluate every time without writing any data to store.
