### ISSUE TITLE
Improve downloading to CloudFile

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#69]
Getting data from HTTP sources into MBrace is a common use case; currently the standard ```cloud { }``` involves the usual creating of a web client, downloading and pushing into a cloudfile. This could be incorporated into the library easily enough (either directly onto CloudFile or perhaps better as an extension method on it), but more than that, for large files it could be written to in parallel - certainly Azure blobs allow for writing to multiple parts of a blob using the API. This would be very useful where you have one extremely large file and want to upload it quickly into Azure.

**Comment by eiriktsarpalis** [comment]
This would make a nice addition to the library code. Might be a silly question, but how can the download of a file via http benefit from using a parallel upload API?

**Comment by isaacabraham** [comment]
I'm actually not thinking about HTTP per se - basically I've been using the ```CloudFile.Create``` overload that takes a ```stream -> async unit``` and providing the stream to the HTTP source (using the stream's CopyTo functionality).

If this could be harnessed by having multiple workers partition the source (seeking to the appropriate partition of the stream) and downloading just that partition, it could work. Obviously this would depend on whether the underlying stream supported seek operations.

The situation I had was several files downloading over HTTP to CloudFiles working great - but one big one must be done on a single worker only. HTTP in general allows resume so I'm assuming that this might somehow be possible.

**Comment by eiriktsarpalis** [comment]
Ah, got it.

Perhaps the parallel upload API could also be used w.r.t. #64. But probably this should be confined to an Azure-specific library? I would assume not all storage services support this.

**Comment by isaacabraham** [comment]
yes, of course. but there's nothing to stop you exposing a specific interface for those services that do. Then the bit that communicates to the runtime implementation can take a different path depending on the capabilities offered by the runtime being used.
