### ISSUE TITLE
Error when using CloudFlow.toArray

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#84]
I get a strange F# compiler error when using MBrace Cloud Flow today – has anyone ever seen this?  It seems to be failing to resolve a reference to a method in Streams.Core.dll, as if there is a version mismatch between the things being referenced.

```
4-cloud-parallel-data-flow.fsx(36,8): error FS0971: Undefined value 'AddRange : !<'T> ArrayCollector <'T> -> ArrayCollector <'T> -> unit
         ! compiled_name! =  AddRange
           membInfo-slotsig! =  []
         # arity<1>[1, 1]'
```

It is when running this code from the starter pack:

```
let streamComputationJob = 
    [| 1..100 |]
    |> CloudFlow.ofArray
    |> CloudFlow.toArray
    |> cluster.CreateProcess
```

Against these dependencies:

```
    FsPickler (1.0.17)
    MBrace.Azure (0.6.5-alpha)
    MBrace.Azure.Standalone (0.6.5-alpha)
    MBrace.Core (0.9.8-alpha)
    MBrace.Flow (0.9.8-alpha)
    MBrace.Runtime.Core (0.9.8-alpha)
    Microsoft.Data.Edm (5.6.4)
    Microsoft.Data.OData (5.6.4)
    Microsoft.Data.Services.Client (5.6.4) - framework: >= net40
    Microsoft.WindowsAzure.ConfigurationManager (3.1.0) - framework: >= net40
    Mono.Cecil (0.9.6.0)
    Newtonsoft.Json (6.0.8) - framework: wpv8.0, >= net40
    Streams (0.3.0)
    System.Spatial (5.6.4)
    Unquote (2.2.2)
    Vagabond (0.6.3)
    WindowsAzure.ServiceBus (2.6.5)
    WindowsAzure.Storage (4.3.0)
``

**Comment by dsyme** [comment]
This also happens against the default paket.lock dependencies used by the starter kit (see below).  Either something is wrong with F# inlining, or something is wrong with the set of assemblies being referenced.  It's a very strange error because the method being referenced definitely exists and Streams.Core.dll hasn't changed in quite a while.


```
NUGET
  remote: https://www.nuget.org/api/v2
  specs:
    FsPickler (1.0.16)
    MBrace.Azure (0.6.5-alpha)
    MBrace.Azure.Standalone (0.6.5-alpha)
    MBrace.Core (0.9.8-alpha)
    MBrace.Flow (0.9.8-alpha)
    MBrace.Runtime.Core (0.9.8-alpha)
    Microsoft.Data.Edm (5.6.3)
    Microsoft.Data.OData (5.6.3)
    Microsoft.Data.Services.Client (5.6.3) - framework: >= net40
    Microsoft.WindowsAzure.ConfigurationManager (3.1.0) - framework: >= net40
    Mono.Cecil (0.9.5.4)
    Newtonsoft.Json (6.0.8) - framework: wpv8.0, >= net40
    Streams (0.3.0)
    System.Spatial (5.6.3)
    Unquote (2.2.2)
    Vagabond (0.6.0)
    WindowsAzure.ServiceBus (2.6.4)
    WindowsAzure.Storage (4.3.0)
```

**Comment by isaacabraham** [comment]
Probably not the reason why, but any reason why there's both MBrace.Azure and MBrace.Azure.Standalone?

**Comment by dsyme** [comment]
This comoes from the resolution of the [paket.dependencies in the root of MBrace.StarterKit](https://github.com/mbraceproject/MBrace.StarterKit/blob/master/paket.dependencies).  The standalone cloud service project uses MBrace.Azure, the HandsOnTutorial uses MBrace.Azure.Standalone.  

I don't think it's the source of the problem but maybe.....

**Comment by isaacabraham** [comment]
I'm just wondering actually now - does the StarterKit have embedded *bundled) dependencies still or are they paketified?

**Comment by krontogiannis** [comment]
I've seen this before in the MBrace.Azure solution (again with the AddRange of Streams.Core.dll). I feel like it's an issue with the inlining (this fails only within an interactive session, standalone compilation is fine). For some reason adding an explicit #r "Streams.Core.dll" makes the error disappear :S

**Comment by dsyme** [comment]
It is odd. Perhaps it's because Streams.Core was not in the overall reference set and couldn't bee implicitly resolved.

Somewhat tangential but I've noticed is that MBrace.Core has a _lot_ of "inline" annotations that probably aren't needed.  I'm not sure anything is gained (and perhaps something is lost) by inlining CloudFlow.toArray for example.    And I'm really not sure any performance is gained by inlining all of [CloudFlow.map](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Flow/Combinators.fs#L242) - or [CloudFlow.fold](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Flow/Combinators.fs#L417).  That's just a heck of a lot of code being inlined and leaking across abstraction boundaries - is there really performance gain here?

**Comment by palladin** [comment]
I think that your point about inline is probably correct. We should probably remove all the inline annotations from the surface API.

**Comment by eiriktsarpalis** [comment]
I agree. Excessive use of inlining forces us to expose things that we shouldn't have and forces almost all consumer code in a single file.

**Comment by dsyme** [comment]
@eiriktsarpalis - did you reopen because the fix didn't work for you, or because of the chat about inlining?  thanks

**Comment by eiriktsarpalis** [comment]
@dsyme I'll leave this open until we sort out the inlining in flow.

**Comment by anirothan** [comment]
excessive inlining of CloudFlows removed in https://github.com/mbraceproject/MBrace.Core/pull/85
