### ISSUE TITLE
Promote common types up from .Core namespace

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#87]
Things like the ```cloud { }``` could (should?) be moved up to the ```MBrace``` namespace. Only types that are either advanced or e.g. interfaces that are not often used directly etc. could be left in ```MBrace.Core```. The same could be done with some of the MBrace.Azure core types e.g. Configuration; in this way you can share a common logical namespace from several different physical assemblies.

This way someone can simply type ```MBrace.``` and see a simple list of the common types that are going to be needed quickly and easily.

**Comment by isaacabraham** [comment]
Sorry - looked at older version, I see that this has already been done in the latest release.

**Comment by eiriktsarpalis** [comment]
Yeah, this was added after #56.

**Comment by dsyme** [comment]
Fwiw I'm not sure about this. It is unusual in mature .NET technologies to have things under a top-level namespace and I always think it's an indicator of something fishy. Will think it over though.

**Comment by dsyme** [comment]
(except System of course)

**Comment by eiriktsarpalis** [comment]
It might be because the common format is Organization.Project. The
namespace used to be Nessos.MBrace but we removed that in favor of a
neutral name.

**Comment by dsyme** [comment]
Yes, though I'll take a good look at the current organization tomorrow, I should have done that before commenting at all! :)

**Comment by isaacabraham** [comment]
If anything having looked at the latest version there's maybe a bit too much at the very top level :)

I'm not a fan of this "physical assembly maps directly to logical namespaces" our having large nested namespaces.

Don - I should point out that in F#4 the Microsoft prefix before FSharp has also been made optional,:)
