### ISSUE TITLE
API consistency on flows and streams

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#92]
If you have an array of items and want to map across them via mbrace, there are (as far as I found) several different ways: -

1. ```CloudFlow.map```. This would seem to be the default mechanism for doing such things - use the ```CloudFlow.ofArray``` combinator and off you go. But you can't easily deal with ```cloud { }``` or ```local { }``` blocks inside these - or if you can, how?
2. ```Cloud.Parallel```. A little more low-level than ```CloudFlow```, and more flexible. but there's a finite size on the amount of items you can chuck at this before it throws an ```ArgumentException``` because of too many processes.
3. ```Workflow.Cloud.Balanced``` has two methods: ```map``` and ```mapLocal```. The former does what you would expect i.e. ```T -> U``` and to all intents and purposes behaves like ```CloudFlow.map```. The latter goes from ```T -> U local``` i.e. it expects to receive a ```local { }``` back. This is useful if you want to do something like access a ```CloudValue``` inside - ```map``` doesn't let you.
4. ```Workflow.Cloud.Sequential``` has a ```map``` method. Except this one goes from ```T -> U cloud```! Why is the signature different on this map to the other ones?

I can see there being two types of uses for this sort of thing: -

1. Standard simple maps i.e. ```T -> U```.
2. Maps that need ```local { }```. This is very useful if you need to go back to the cluster for anything inside a map.

What's the recommended way of doing them given the options identified above (and are there any others that I've missed)?

**Comment by isaacabraham** [comment]
Just adding to my comment above - there's also ```mapLocal``` for ```CloudFlow``` as well.

**Comment by eiriktsarpalis** [comment]
This is a more or less comprehensive rundown of what is currently possible out of the box with MBrace. Some comments regarding your points:
1. Like you said it is possible to use the `CloudFlow.*Local` array of combinators for composing with workflows, however these were included as an afterthought. CloudFlow focuses on primarily CPU-bound combinator pipelines acting on large datasets.
2. `Cloud.Parallel` is the primitive on which everything else relies on. When everything else fails, `Cloud.Parallel` is the way to go, it needs however to be used with care.
4. `MBrace.Workflows.Cloud.Sequential.map` is a combinator that composes with cloud (i.e. distributed) map functions, which however iterates through each of the inputs elements in sequential fashion. This has application in iterative workflows.

**Comment by dsyme** [comment]
When I look at this list, I still get the feeling that Workflow.* should be an add-on library or sample, rather than part of the core API.  I know they are used internally in MBrace and they are instructive, but are they core to the programming model?  For example, we don't teach them in the starter kit (and I don't know if we should, given that it gives even more ways to do things).

**Comment by isaacabraham** [comment]
I had a good chat with @eiriktsarpalis about this. To me, the part that *is* useful in the Balanced operations. One thing I noticed is that for non-IO bound operations, particularly with the ```local``` versions e.g. ```mapLocal``` of ```CloudFlow```, it does not perform nearly as well as ```Balanced``` e.g. I did a variant of doing sum of squares of 10000 items, with ```Balanced``` it took just a few seconds but for ```CloudFlow``` it took 9minutes odd - it's just not what it's designed for.

In addition, ```Cloud.Parallel``` is (as far as I'm concerned anyway) no where near as good as the ```map``` or ```mapLocal``` functions in ```Balanced``` - ```Parallel``` has limits on size, it doesn't shared intelligently like ```Balanced``` (as far as I know) etc..

IMHO the Balanced stuff (or one of them - that or Local.Parallel) should be moved up the stack as some sort of simple set of operators - maybe even just ```map``` and ```mapLocal```. The others should probably be hidden away. Frankly I never even knew that they existed until this weekend. But you need *something* apart from manually constructing ```cloud { }``` and using ```CloudFlow``` for simple distribution of operations.

**Comment by palladin** [comment]
the following took ~ 3secs
```
let proc = 
    CloudFlow.OfArray [|1..10000|]
    |> CloudFlow.mapLocal (fun x -> local { return x * x })
    |> CloudFlow.toArray
    |> runtime.CreateProcess
```

**Comment by dsyme** [comment]
> it took just a few seconds but for  CloudFlow  it took 9minutes odd 

> the following took ~ 3secs

@isaacabraham @eiriktsarpalis  - In both cases, how many machines did you have in your cluster?  I've experienced long run times when there are many machines (> 10) but I've never really been able to work out what's going on.

**Comment by palladin** [comment]
I tested on a cluster with 4 medium instances

**Comment by isaacabraham** [comment]
It wasn't exactly that - it was something similar using a dereferenced CloudValue - I'll try to find the sample but I sent it to @eiriktsarpalis the other day.

**Comment by dsyme** [comment]
1 Azure machine - 7.5sec
10 Azure machines - 11.3sec
50 Azure machines - 17.5sec
100 Azure machines - 48.9sec

Any idea why?  cc @krontogiannis

**Comment by palladin** [comment]
@dsyme I'm pretty sure that it is a behaviour of the service bus, because if you repeatly execute the same CloudFlow computation you will see that the average execution time is about ~10secs
I tested the above mentioned CloudFlow on a cluster of 90 azure medium instances.
@krontogiannis Maybe is some kind of Service bus warm up?

**Comment by palladin** [comment]
It seems that Service bus has some unpredictable behaviour
http://stackoverflow.com/questions/29425653/azure-service-bus-queue-extremely-slow

**Comment by dsyme** [comment]
The slowdowns are dramatic :)  

From an answer to that question:

> We partitioned our queues and then removed duplicate detection and things got much better. Microsoft acknowledged there were locking issues which they were working on a solution towards. Duplicate detection restricts your queue to one partition, so this alone made no difference. They told me that they would alert us when the fix was applied and we are going to try turning on duplicate detection again.

Is any of this relevant?

**Comment by palladin** [comment]
@dsyme I'm investigating it with @krontogiannis to see what we can do and if it is relevant and in what way with https://github.com/mbraceproject/MBrace.Azure/issues/79

**Comment by krontogiannis** [comment]
@dsyme For both queues used by the runtime duplicate detection is disabled (that's the default) and partitioning is enabled.

As @palladin said these slow downs in the communication with Service Bus doesn't seem to persist in subsequent runs (so it doesn't seem like a scaling issue, from 10 to 90 machines the code run in ~10 seconds). We need to check if there is a way to bypass this weird behaviour somehow (post and consume empty messages http://msdn.microsoft.com/en-us/library/ms166135.aspx?)

**Comment by isaacabraham** [comment]
@palladin I've run that perf test again, it comes out fine now with CloudFlow - 5 seconds versus 2 seconds for Cloud.Balanced. So not that much worse than I originally saw - perhaps some large bound value got sent across for the ride or something and had an adverse effect.

More than ever, the fact that the timings for something like this are not far out in real terms from one another illustrates the need to only surface the important methods to the end user and hide away other ones under an e.g. ```Advanced.``` namespace.

**Comment by dsyme** [comment]
@palladin - I ran the CloudFlow above on 50 and 100 instances and got execution times in the order of 8s-14s.  Times still seem to be consistently marginally longer with more instances. 14s still seems a long time to have 100 VMs take 100 items out of a queue though....

**Comment by palladin** [comment]
@dsyme In the next version of MBrace.Azure we are going to have traces/logs for each individual job like
```
let proc = 
    CloudFlow.OfArray [|1..10000|]
    |> CloudFlow.map (fun x -> x * x)
    |> CloudFlow.toArray
    |> runtime.CreateProcess

proc.ShowJobs()
```
and it will help us in the investigation of the weired Azure behaviours.

**Comment by dsyme** [comment]
Great, thanks!

**Comment by dsyme** [comment]
I think this particular discussion is at an end and can be closed out?

**Comment by isaacabraham** [comment]
The perf and service bus issues yes. Not sure if we came to a conclusion regarding the original discussion regarding balanced / sequential / parallel modules.
