### ISSUE TITLE
Suggestion: clarify Jobs columns for GetProcesses()

### ISSUE THREAD

**Issue by mathias-brandewinder** [mbraceproject/MBrace.Core#94]
When I call cluster.GetProcesses(), I see a summary which includes a header for Jobs, with 4 columns underneath.
I suspect these 4 columns must be total jobs, faulted, running and done, however as is it's difficult to know what is what. 
I suggest clarifying what each column is, perhaps with RUN/ ERR/ TOT/ DONE, or something similar.

**Comment by krontogiannis** [comment]
At the lower left corner of the ShowProcesses output there is a note about what that column means
```
Jobs : Active / Faulted / Completed / Total
```
Didn't add this to the header as it would become too wide imo.

Anyway these counters are refactored in [jobinfo](https://github.com/krontogiannis/MBrace.Azure/tree/jobinfo), we might as well change the visual representation.

**Comment by mathias-brandewinder** [comment]
Duh - how could I miss that!?
Fair point regarding width. As a suggestion there, maybe you could remove the ticks at the end of timing information.
