### ISSUE TITLE
CloudFile.Upload: why sourcePath: seq<string> ? 

### ISSUE THREAD

**Issue by mathias-brandewinder** [mbraceproject/MBrace.Core#95]
I was a bit surprised to see that CloudFile.Upload takes in a sequence of paths, instead of the path to a single file. I would have expected a single-filepath signature, but I am probably missing a use case / scenario. Can you clarify why you went this route?

**Comment by eiriktsarpalis** [comment]
I'm pretty certain that there are two overloads of `CloudFile.Upload`, one for single files and one for multiple files. No?

**Comment by mathias-brandewinder** [comment]
Dammit what's wrong with me today. Sorry about that!

**Comment by eiriktsarpalis** [comment]
Haha, no worries!
