### ISSUE TITLE
Explicitly remove a worker from the pool

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Core#99]
If you attach a local worker (for example), how can you remove it from the pool? If you just close the console window process, it still remains for a while as a worker in the pool. Work gets allocated to it, and jobs don't complete until the pool realises that the worker has died.

**Comment by eiriktsarpalis** [comment]
This is really an MBrace.Azure. Could you re-post this there?

**Comment by isaacabraham** [comment]
Sure - not sure if the mechanism that detects "dead" workers (or having the ability to explicitly remove a worker) is an MBrace.Azure thing though?
